# Generated by Django 4.1.3 on 2022-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image')),
                ('post_video', models.ImageField(blank=True, null=True, upload_to='post_video')),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='Post_posted_time')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
            ],
        ),
    ]
