# Generated by Django 4.1.3 on 2022-11-17 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrate_react', to=settings.AUTH_USER_MODEL)),
                ('curious', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curious_react', to=settings.AUTH_USER_MODEL)),
                ('insightful', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insightful_react', to=settings.AUTH_USER_MODEL)),
                ('like', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_react', to=settings.AUTH_USER_MODEL)),
                ('love', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='love_react', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='react', to='posts.post')),
                ('support', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_react', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
