# Generated by Django 4.1.3 on 2022-11-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_reacty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='up_vote_by',
            new_name='like',
        ),
    ]
