# Generated by Django 4.1.3 on 2022-11-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_rename_up_vote_by_vote_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='like',
            new_name='up_vote_by',
        ),
    ]
