# Generated by Django 4.1.3 on 2022-11-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_followapi_remove_friend_receiver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followapi',
            unique_together=set(),
        ),
    ]
