# Generated by Django 4.1.3 on 2022-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
    ]
