# Generated by Django 4.1.3 on 2022-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented', models.CharField(max_length=4000)),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment_image')),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='comment_posted_time')),
            ],
        ),
    ]
