# Generated by Django 4.1.3 on 2022-11-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=4000)),
                ('reply_date', models.DateField(auto_now_add=True)),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='reply_posted_time')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='comment.comment')),
            ],
        ),
    ]
